version: "3.8"

services:
  mariadb:
    build:
      context: ./initdb
      dockerfile: Dockerfile
    restart: always
    container_name: luigi-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: solvam
      MARIADB_DATABASE: solar_screen
      MARIADB_INIT_SCRIPTS_ALWAYS_EXECUTE: "true"
    # No exponer 3306 al host por seguridad
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - solvam

  # Acceso a phpMyAdmin solo desde el host (bind a localhost).
  # Si quieres acceder remotamente usa Nginx Proxy Manager con autenticación o SSH tunnel.
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    container_name: luigi-phpmyadmin
    ports:
      - "127.0.0.1:8080:80"   # solo accesible desde el servidor (puedes quitar esto y usar NPM si prefieres)
    environment:
      PMA_HOST: luigi-mariadb
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: solvam
      MYSQL_ROOT_PASSWORD: solvam
    networks:
      - solvam
    depends_on:
      - mariadb

  codeigniter:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: luigi-backend
    volumes:
      - ./backend:/var/www/html
    expose:
      - "80"            # expuesto solo a la red docker, NO al host
    depends_on:
      - mariadb
    networks:
      - solvam

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      # Si tu Dockerfile tiene multi-stage, usa target: production si lo has definido
      # target: production
    container_name: luigi-frontend
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    expose:
      - "80"            # en producción lo ideal es servir con nginx dentro del contenedor en el puerto 80
    environment:
      - NODE_ENV=production
    depends_on:
      - codeigniter
    networks:
      - solvam
    stdin_open: true
    tty: true

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    container_name: nginx-proxy-manager
    ports:
      - "80:80"   # HTTP
      - "81:81"   # panel de administración NPM
      - "443:443" # HTTPS
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
    networks:
      - solvam

networks:
  solvam:
    driver: bridge

volumes:
  mariadb_data:
  frontend_node_modules:
